[package]
name = "etmar-logistics"
version = "0.1.0"
edition = "2021"

[workspace]
members = ['migration']

[workspace.dependencies]
dotenv = "0.15.0"
tokio = { version = "1.41.1", features = ["full"] }


[dependencies]
migration = { path = "./migration" }
axum = "0.7.9"
tokio.workspace = true
dotenv.workspace = true
garde = { version = "0.20.0", features = ["derive", "serde"] }
hyper-util = "0.1.10"
prost = "0.13.4"
serde = { version = "1.0.215", features = ["derive"] }
sqlx = { version = "0.8.2", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "derive",
  "macros",
  "migrate",
  "uuid",
  "chrono",
  "json",
] }
tokio-stream = "0.1.17"
tonic = "0.12.3"
tonic-web = "0.12.3"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = [
  "catch-panic",
  "compression-gzip",
  "cors",
  "decompression-gzip",
  "fs",
  "limit",
  "request-id",
  "sensitive-headers",
  "timeout",
  "trace",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
sea-orm = { version = "1.1.3", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
] }
futures = "0.3.31"
test-log = "0.2.16"

[build-dependencies]
tonic-build = "0.12.3"
