[package]
name = "logistics-management-system"
version = "0.4.1"
edition = "2024"
authors = [
  "Karl Robeck Alferez <karlalferezfx@gmail.com>",
  "Mhell Francis Bergonio <bergonio.mhell101001@gmail.com>",
]

[[bin]]
name = "backend"
path = "cmd/backend.rs"

[[bin]]
name = "frontend"
path = "cmd/frontend.rs"

[[bin]]
name = "seed"
path = "cmd/seed.rs"

[workspace]
members = ["crate-proto", "crate-utils", "extensions/*", "services/*"]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[build]
rustflags = [
  "-C",
  "target-cpu=native",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-Z",
  "threads=8",
]

[workspace.dependencies]
prost = "0.13.4"
serde = { version = "1.0.215", features = ["derive"] }
sqlx = { version = "0.8.2", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "derive",
  "macros",
  "migrate",
  "uuid",
  "chrono",
  "json",
] }
tonic = { version = "0.12.3", features = ["router"] }
jwt = "0.16.0"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio-stream = "0.1.17"
tower = "0.5.2"
futures = "0.3.31"
garde = { version = "0.20.0", features = ["derive", "serde", "email"] }
uuid = { version = "1.12.1", features = ["v4"] }
axum = "0.7.9"
dotenv = "0.15.0"
tower-http = { version = "0.6.2", features = [
  "catch-panic",
  "compression-gzip",
  "cors",
  "decompression-gzip",
  "fs",
  "limit",
  "request-id",
  "sensitive-headers",
  "timeout",
  "trace",
] }
test-log = "0.2.16"
tokio-util = "0.7.13"
clap = { version = "4.5.26", features = ["derive", "string"] }
askama = "0.12.1"
askama_axum = "0.4.0"
axum-extra = { version = "0.9.0", features = ["cookie"] }

[dependencies]
service-storage = { path = "services/storage" }
service-authentication = { path = "services/authentication" }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
tonic = { workspace = true }
dotenv = { workspace = true }
tower-http = { workspace = true }
test-log = { workspace = true }
tokio-util = { workspace = true }
clap = { workspace = true }
axum = { workspace = true }
frontend-authentication = { path = "extensions/frontend-authentication" }
crate-proto = { path = "crate-proto" }
base = { path = "extensions/base" }
axum-extra = { workspace = true }
