[package]
name = "logistics-management-system"
version = "0.5.0"
edition = "2021"
authors = [
  "Karl Robeck Alferez <karlalferezfx@gmail.com>",
  "Mhell Francis Bergonio <bergonio.mhell101001@gmail.com>",
]

[[bin]]
name = "backend"
path = "cmd/backend.rs"

[workspace]
members = [
  "crates/lib-proto",
  "crates/lib-utils",
  "crates/service-human-resource",
  "crates/service-authentication",
  "crates/service-storage",
  "crates/lib-core",
]


[workspace.dependencies]
prost = "0.13.4"
serde = { version = "1.0.215", features = ["derive"] }
sqlx = { version = "0.8.2", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "derive",
  "macros",
  "migrate",
  "uuid",
  "chrono",
  "json",
] }
tonic = { version = "0.12.3", features = ["router"] }
jwt = "0.16.0"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio-stream = "0.1.17"
tower = "0.5.2"
futures = "0.3.31"
garde = { version = "0.20.0", features = ["derive", "serde", "email"] }
uuid = { version = "1.12.1", features = ["v4"] }
axum = "0.7.9"
dotenv = "0.15.0"
tower-http = { version = "0.6.2", features = [
  "catch-panic",
  "compression-gzip",
  "cors",
  "decompression-gzip",
  "fs",
  "limit",
  "request-id",
  "sensitive-headers",
  "timeout",
  "trace",
] }
test-log = "0.2.16"
tokio-util = "0.7.13"
clap = { version = "4.5.26", features = ["derive", "string"] }
askama = "0.12.1"
askama_axum = "0.4.0"
axum-extra = { version = "0.9.0", features = ["cookie"] }
sea-query = { version = "0.32.2", features = [
  "thread-safe",
  "backend-postgres",
  "postgres-array",
] }
sea-query-binder = { version = "0.7.0", features = [
  "sqlx-postgres",
  "postgres-array",
] }
tracing-test = "0.2.5"

[dependencies]
service-storage = { path = "./crates/service-storage" }
service-authentication = { path = "./crates/service-authentication" }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
tonic = { workspace = true }
dotenv = { workspace = true }
tower-http = { workspace = true }
test-log = { workspace = true }
tokio-util = { workspace = true }
clap = { workspace = true }
axum = { workspace = true }
lib-proto = { path = "./crates/lib-proto" }
axum-extra = { workspace = true }
sea-query = { workspace = true }
