services:
  postgres:
    image: postgres:17.2-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
