//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use super::sea_orm_active_enums::EmployeeContractType;
use super::sea_orm_active_enums::EmployeeRole;
use super::sea_orm_active_enums::EmployeeStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "logistics", table_name = "employee")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub avatar_id: Option<Uuid>,
    pub cover_photo_id: Option<Uuid>,
    pub first_name: String,
    pub middle_name: String,
    pub last_name: String,
    pub tel_number: Option<String>,
    pub mobile_number: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub role: EmployeeRole,
    pub status: EmployeeStatus,
    pub contract_type: EmployeeContractType,
    pub phil_nat_id: String,
    pub birth_date: Date,
    pub special_interests: Option<Vec<String>>,
    pub learning_institutions: Vec<String>,
    pub auth_user_id: Uuid,
    pub spouse_first_name: Option<String>,
    pub spouse_middle_name: Option<String>,
    pub spouse_last_name: Option<String>,
    pub spouse_employer: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::emergency_information::Entity")]
    EmergencyInformation,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::emergency_information::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmergencyInformation.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
