//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub mod prelude;

pub mod department;
pub mod department_employees;
pub mod emergency_information;
pub mod employee;
pub mod extensions;
pub mod file;
pub mod file_access;
pub mod job_information;
pub mod personnel_action;
pub mod sea_orm_active_enums;
pub mod users;
