//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub mod prelude;

pub mod department;
pub mod emergency_information;
pub mod employee;
pub mod file;
pub mod job_information;
pub mod permissions;
pub mod sea_orm_active_enums;
pub mod users;
