//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::department::Entity as Department;
pub use super::department_employees::Entity as DepartmentEmployees;
pub use super::emergency_information::Entity as EmergencyInformation;
pub use super::employee::Entity as Employee;
pub use super::file::Entity as File;
pub use super::file_access::Entity as FileAccess;
pub use super::job_information::Entity as JobInformation;
pub use super::personnel_action::Entity as PersonnelAction;
pub use super::users::Entity as Users;
