//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_type")]
pub enum AuthType {
    #[sea_orm(string_value = "basic_auth")]
    BasicAuth,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "employee_contract_type")]
pub enum EmployeeContractType {
    #[sea_orm(string_value = "FullTime")]
    FullTime,
    #[sea_orm(string_value = "PartTime")]
    PartTime,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "employee_role")]
pub enum EmployeeRole {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Manager")]
    Manager,
    #[sea_orm(string_value = "Employee")]
    Employee,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "employee_status")]
pub enum EmployeeStatus {
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Inactive")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "pan_action_status")]
pub enum PanActionStatus {
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Approved")]
    Approved,
    #[sea_orm(string_value = "Rejected")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "pan_action_type")]
pub enum PanActionType {
    #[sea_orm(string_value = "Hire")]
    Hire,
    #[sea_orm(string_value = "Promotion")]
    Promotion,
    #[sea_orm(string_value = "SalaryAdjustment")]
    SalaryAdjustment,
    #[sea_orm(string_value = "Termination")]
    Termination,
    #[sea_orm(string_value = "Leave")]
    Leave,
    #[sea_orm(string_value = "Transfer")]
    Transfer,
}
