//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use super::sea_orm_active_enums::AuthType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "logistics", table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub auth_type: AuthType,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub create_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::employee::Entity")]
    Employee,
    #[sea_orm(has_many = "super::file::Entity")]
    File,
    #[sea_orm(has_many = "super::file_access::Entity")]
    FileAccess,
}

impl Related<super::employee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employee.def()
    }
}

impl Related<super::file_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAccess.def()
    }
}

impl Related<super::file::Entity> for Entity {
    fn to() -> RelationDef {
        super::file_access::Relation::File.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::file_access::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
