//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "contract_type_enum")]
pub enum ContractTypeEnum {
    #[sea_orm(string_value = "full_time")]
    FullTime,
    #[sea_orm(string_value = "part_time")]
    PartTime,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role_enum")]
pub enum RoleEnum {
    #[sea_orm(string_value = "super_admin")]
    SuperAdmin,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "employee")]
    Employee,
    #[sea_orm(string_value = "client")]
    Client,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sex_enum")]
pub enum SexEnum {
    #[sea_orm(string_value = "male")]
    Male,
    #[sea_orm(string_value = "female")]
    Female,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "task_status_enum")]
pub enum TaskStatusEnum {
    #[sea_orm(string_value = "unassigned")]
    Unassigned,
    #[sea_orm(string_value = "in_progress")]
    InProgress,
    #[sea_orm(string_value = "review")]
    Review,
    #[sea_orm(string_value = "done")]
    Done,
}
