[package]
name = "lib-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper-util = "0.1.10"
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tower = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
