// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "auth.proto" (package "auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { Empty } from "./google/protobuf/empty";
import type { AuthBasicUpdatePassword } from "./auth";
import type { AuthBasicRegisterRequest } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AuthResponse } from "./auth";
import type { AuthBasicLoginRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: BasicLogin(auth.AuthBasicLoginRequest) returns (auth.AuthResponse);
     */
    basicLogin(input: AuthBasicLoginRequest, options?: RpcOptions): UnaryCall<AuthBasicLoginRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: BasicRegister(auth.AuthBasicRegisterRequest) returns (auth.AuthResponse);
     */
    basicRegister(input: AuthBasicRegisterRequest, options?: RpcOptions): UnaryCall<AuthBasicRegisterRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: BasicUpdatePassword(auth.AuthBasicUpdatePassword) returns (google.protobuf.Empty);
     */
    basicUpdatePassword(input: AuthBasicUpdatePassword, options?: RpcOptions): UnaryCall<AuthBasicUpdatePassword, Empty>;
}
/**
 * @generated from protobuf service auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: BasicLogin(auth.AuthBasicLoginRequest) returns (auth.AuthResponse);
     */
    basicLogin(input: AuthBasicLoginRequest, options?: RpcOptions): UnaryCall<AuthBasicLoginRequest, AuthResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthBasicLoginRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BasicRegister(auth.AuthBasicRegisterRequest) returns (auth.AuthResponse);
     */
    basicRegister(input: AuthBasicRegisterRequest, options?: RpcOptions): UnaryCall<AuthBasicRegisterRequest, AuthResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthBasicRegisterRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BasicUpdatePassword(auth.AuthBasicUpdatePassword) returns (google.protobuf.Empty);
     */
    basicUpdatePassword(input: AuthBasicUpdatePassword, options?: RpcOptions): UnaryCall<AuthBasicUpdatePassword, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthBasicUpdatePassword, Empty>("unary", this._transport, method, opt, input);
    }
}
