// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package humanresource

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/F-orge/logistics-management-system/src/views/components"
	"github.com/F-orge/logistics-management-system/src/views/layouts"
	"github.com/F-orge/logistics-management-system/src/views/utils"
	"github.com/labstack/echo/v4"
)

func (h *HumanResource) EmployeePageHandler(c echo.Context) error {
	return utils.Render(EmployeePage(c), c)
}

func EmployeePageMetadata() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<title>Management  | Employee</title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func EmployeePage(c echo.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<article class=\"overflow-y-auto\"><section class=\"p-4 border-b\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatsComponent([]components.StatsComponentProps{
				{LabelIcon: "icon-[lucide--users-round]", Label: "Total Employees", Value: "10/10", ValueLabel: "Total Count"},
				{LabelIcon: "icon-[lucide--user-round-check]", Label: "Currently Working", Value: "5", ValueLabel: "Working Now"},
				{LabelIcon: "icon-[lucide--file-user]", Label: "Currently Idle", Value: "3", ValueLabel: "Idle Now"},
				{LabelIcon: "icon-[lucide--user-x]", Label: "On Leave", Value: "2", ValueLabel: "On Leave"},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section><section class=\"p-4 border-b space-y-5\"><div class=\"flex flex-row items-center justify-between\"><div><h4 class=\"heading-4\">Employee List</h4><span class=\"muted\">Employee directory</span></div><div class=\"space-x-2.5\"><button class=\"btn btn-primary\"><div class=\"icon-[lucide--user-plus]\"></div><span>Employee</span></button> <button class=\"btn btn-outline\"><div class=\"icon-[lucide--sliders-horizontal]\"></div><span>View</span></button></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Table(components.TableProps{
				Columns: []string{
					"First Name", "Middle Name", "Last Name", "Current Work", "Status", "Position", "Contract Type",
				},
				Rows: [][]string{
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
					[]string{
						"John", "James", "Doe", "4", "Active", "Manager", "Full Time",
					},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</section></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.DashboardPage(layouts.DashboardPageProps{
			Title:         "Employees",
			Metadata:      EmployeePageMetadata(),
			ServerContext: c,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
