[package]
name = "marketing"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
rinja = { workspace = true }
rinja_axum = { workspace = true }
include_dir = { workspace = true }
tower-serve-static = { workspace = true }
