services:
  postgres:
    build:
      context: ../
      dockerfile: .docker/postgres.dockerfile
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
    volumes:
      - postgres-storage:/var/lib/postgresql/data
  nextjs:
    depends_on:
      - rust
    build:
      context: ../
      dockerfile: .docker/nextjs.dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal
    env_file:
      - ../.env
  rust:
    build:
      context: ../
      dockerfile: .docker/rust.dockerfile
    networks:
      - internal
    volumes:
      - rust-storage:/app/storage
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
networks:
  internal:
volumes:
  rust-storage:
  postgres-storage:
