[package]
name = "lib-proto"
version = "0.2.0"
edition = "2021"

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
sqlx = { workspace = true }
sea-orm = { workspace = true }

[build-dependencies]
tonic-build = "0.12.3"
