name: Rust pull request

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
	runs-on: [self-hosted, linux, x64]
	steps:
	  - uses: actions/checkout@v2
	  - name: Install Rust
		uses: actions-rs/toolchain@v1
		with:
		  toolchain: stable
	  - name: Install Clippy
		run: cargo install clippy
	  - name: Run Clippy
		run: cargo clippy --all-targets --all-features -- -D warnings
  build:
	runs-on: [self-hosted, linux, x64]
	steps:
	  - uses: actions/checkout@v2
	  - name: Install Rust
		uses: actions-rs/toolchain@v1
		with:
		  toolchain: stable
	  - name: Install Clippy
		run: cargo install clippy
	  - name: Run Clippy
		run: cargo clippy --all-targets --all-features -- -D warnings