name: Rust pull request

on:
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "on"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - name: Run Postgres in compose
        run: docker compose -f dev.compose.yaml up postgres -d
      - name: Copy .env.development to .env
        run: cp .env.development .env
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install SQLX CLI
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      - name: Prepare database
        run: cargo sqlx prepare
      - name: Run migrations
        run: sqlx migrate
      - name: Lint with Clippy
        run: cargo clippy
      - name: Build with Cargo
        run: cargo build
      - name: Test with Cargo
        run: cargo test
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
