name: Rust pull request

on:
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "on"
      RUSTC_WRAPPER: "sccache"
      ADDRESS: "0.0.0.0"
      DOMAIN: "localhost"
      PORT: "3000"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
    steps:
      - uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Run make Install
        run: make install
      - name: Lint with Clippy
        run: cargo clippy
      - name: Test with Cargo
        run: cargo test
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
