name: Rust pull request

on:
  push:
    branches: 
      - main
  pull_request:
    branches:    
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: [self-hosted,linux,x64]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Lint with Clippy
      run: cargo clippy --verbose
    - name: Build with Cargo
      run: cargo build --verbose
    - name: Test with Cargo
      run: cargo test --verbose
    