name: Rust pull request

on:
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Lint with Clippy
        run: cargo clippy
      - name: Build with Cargo
        run: cargo build
      - name: Test with Cargo
        run: cargo test
  typescript:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Lint with Deno
        run: deno lint
      - name: Format with Deno
        run: deno fmt
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Test using vitest
        run: npm test
