name: Rust pull request

on:
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "on"
      RUSTC_WRAPPER: "sccache"
      ADDRESS: "0.0.0.0"
      DOMAIN: "localhost"
      PORT: "3000"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Run make Install
        run: make install
      - name: Lint Project
        run: make lint
      - name: Test Project
        run: make test
